source 'https://rubygems.org'
#ruby '2.0.0'
#ruby-gemset=railstutorial_rails_4_0

gem 'rails', '4.0.2'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'bcrypt-ruby'

gem 'sidekiq'
gem 'unf' 
gem 'debugger', group: [:development, :test]
gem 'letter_opener', group: :development
group :development, :test do
  
  gem 'sqlite3'
  gem 'rspec-rails', '2.13.1'
  gem 'guard-rspec', '2.5.0'
  gem 'spork-rails', '4.0.0'
  gem 'guard-spork', '1.5.0'
  gem 'childprocess', '0.3.6'
  gem "launchy", "~> 2.3.0"
  
end 
gem 'exception_notification'
gem 'font-awesome-sass'
gem "bullet", :group => "development"

group :test do
  gem 'factory_girl_rails', '4.2.1'
 
  gem "faker", "~> 1.2.0"

  gem 'cucumber-rails', '1.4.0', :require => false
  gem 'database_cleaner'
 
end
group :test do
  gem 'capybara', "~> 2.1.0"
  gem "poltergeist", "~> 1.4.1"
  gem 'shoulda-matchers'
end
gem 'newrelic_rpm'
gem 'sass-rails', '4.0.1'
gem 'uglifier', '2.1.1'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.0.4'
gem 'jquery-ui-rails'
gem 'hpricot'
group :doc do
  gem 'sdoc', '0.3.20', require: false
end
gem 'pg', '0.15.1'
group :production do
  gem 'unicorn'
  gem 'rails_12factor', '0.0.2'
end
